// <auto-generated />
using EntityDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityDatabase.Migrations
{
    [DbContext(typeof(MusicOfHeartDbContext))]
    [Migration("20241019212639_seed_correct_data")]
    partial class seed_correct_data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityDatabase.Models.Band", b =>
                {
                    b.Property<int>("BandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BandId"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BandId");

                    b.ToTable("Bands");

                    b.HasData(
                        new
                        {
                            BandId = 1,
                            Country = "India",
                            FirstName = "Coke Studio 5"
                        },
                        new
                        {
                            BandId = 2,
                            Country = "Latin America",
                            FirstName = "Veps spiders"
                        },
                        new
                        {
                            BandId = 3,
                            Country = "Norway",
                            FirstName = "Ola Nordman band"
                        });
                });

            modelBuilder.Entity("EntityDatabase.Models.Instrument", b =>
                {
                    b.Property<int>("InstrumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstrumentId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstrumentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstrumentId");

                    b.ToTable("Instruments");

                    b.HasData(
                        new
                        {
                            InstrumentId = 1,
                            Description = "Black color piano",
                            InstrumentName = "Piano"
                        },
                        new
                        {
                            InstrumentId = 2,
                            Description = "Indian traditional sitar",
                            InstrumentName = "Sitar"
                        },
                        new
                        {
                            InstrumentId = 3,
                            Description = "Electric gitar",
                            InstrumentName = "Gitar"
                        });
                });

            modelBuilder.Entity("EntityDatabase.Models.Musician", b =>
                {
                    b.Property<int>("MusicianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusicianId"));

                    b.Property<int>("BandId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusicianId");

                    b.HasIndex("BandId");

                    b.HasIndex("InstrumentId");

                    b.ToTable("Musicians");

                    b.HasData(
                        new
                        {
                            MusicianId = 1,
                            BandId = 1,
                            FirstName = "Raju",
                            InstrumentId = 2,
                            LastName = "Kumar",
                            Origin = "Indian musician"
                        },
                        new
                        {
                            MusicianId = 2,
                            BandId = 2,
                            FirstName = "Vinod",
                            InstrumentId = 3,
                            LastName = "Srivastav",
                            Origin = "American indian musician"
                        },
                        new
                        {
                            MusicianId = 3,
                            BandId = 2,
                            FirstName = "Ram",
                            InstrumentId = 1,
                            LastName = "Gopal",
                            Origin = "British Indian musician"
                        });
                });

            modelBuilder.Entity("EntityDatabase.Models.Musician", b =>
                {
                    b.HasOne("EntityDatabase.Models.Band", "Band")
                        .WithMany("Musicians")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityDatabase.Models.Instrument", "Instrument")
                        .WithMany("Musicians")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("EntityDatabase.Models.Band", b =>
                {
                    b.Navigation("Musicians");
                });

            modelBuilder.Entity("EntityDatabase.Models.Instrument", b =>
                {
                    b.Navigation("Musicians");
                });
#pragma warning restore 612, 618
        }
    }
}
